version: '3'

services:
  postgres:
    image: postgres:14-alpine3.14
    ports:
      - "5423:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=contacts
    volumes:
      - /schema.sql:docker-entrypoint-initdb.d/schema.sql
      - /data.sql:docker-entrypoint-initdb.d/data.sql